# **Running the baseline**
<a target="_blank" href="https://colab.research.google.com/github/raphaelrubrice/BornToOverfit/blob/raph/baseline.ipynb"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/> </a>  

## **Colab setup**

In [1]:
from google.colab import drive
drive.mount('/content/drive')
# to avoid having the data on your drive
%cd /content

Mounted at /content/drive
/content


In [2]:
!git clone https://github.com/raphaelrubrice/BornToOverfit.git
%cd BornToOverfit
!git checkout raph

Cloning into 'BornToOverfit'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 28 (delta 9), reused 22 (delta 7), pack-reused 0 (from 0)
Receiving objects: 100% (28/28), 14.01 KiB | 7.00 MiB/s, done.
Resolving deltas: 100% (9/9), done.
/content/BornToOverfit
Branch 'raph' set up to track remote branch 'raph' from 'origin'.
Switched to a new branch 'raph'


Installing requirements

In [3]:
!pip install -r data_baseline/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 3.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 33.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 66.4 MB/s eta 0:00:00


Downloading the data

In [9]:
!cp -r /content/drive/MyDrive/Kaggle_ALTEGRAD/data /content/BornToOverfit/data_baseline/.

## **Scripts**

In [10]:
!python data_baseline/inspect_graph_data.py

INSPECTING GRAPH DATA FILES

Loading: /content/BornToOverfit/data_baseline/data/train_graphs.pkl
Total graphs: 31008

Graph type: Data

All graph attributes:
  ['edge_index', 'edge_attr', 'x', 'id', 'description']
Node features: torch.Size([40, 9])
Edge indices: torch.Size([2, 86])
Edge features: torch.Size([86, 3])

Sample graph:
  Graph 1:
    ID: 0
    Nodes: 40
    Edges: 86
    Node features (first 3 nodes):
tensor([[6, 0, 3, 5, 1, 0, 3, 1, 1],
        [7, 0, 2, 5, 0, 0, 3, 1, 1],
        [6, 0, 3, 5, 0, 0, 3, 1, 1]])
    Edge indices (first 5 edges):
tensor([[0, 0, 1, 1, 2],
        [1, 5, 0, 2, 1]])
    Edge attributes (first 5 edges):
tensor([[12,  0,  1],
        [12,  0,  1],
        [12,  0,  1],
        [12,  0,  1],
        [12,  0,  1]])
    Description: The molecule is tetraanion of ADP-D-ribose 2'-phosphate. It has a role as a human metabolite. It is a conjugate base of an ADP-D-ribose 2'-phosphate....

Nodes: min=1, max=574, avg=32.1
Edges: min=0, max=1284, avg=66.7
Gr

In [ ]:
#!python data_baseline/generate_description_embeddings.py

python3: can't open file '/content/BornToOverfit/data_baseline/generate_description_embeddings.py': [Errno 2] No such file or directory


In [11]:
!python data_baseline/train_gcn.py

Device: cuda
Loading graphs from: /content/BornToOverfit/data_baseline/data/train_graphs.pkl
Loaded 31008 graphs
Loading graphs from: /content/BornToOverfit/data_baseline/data/validation_graphs.pkl
Loaded 1000 graphs
Epoch 1/5 - loss=0.0001 - val={'MRR': 0.013431530445814133, 'R@1': 0.003000000026077032, 'Hit@1': 0.003000000026077032, 'R@5': 0.01100000087171793, 'Hit@5': 0.01100000087171793, 'R@10': 0.02200000174343586, 'Hit@10': 0.02200000174343586}
Loading graphs from: /content/BornToOverfit/data_baseline/data/validation_graphs.pkl
Loaded 1000 graphs
Epoch 2/5 - loss=0.0001 - val={'MRR': 0.013609470799565315, 'R@1': 0.0020000000949949026, 'Hit@1': 0.0020000000949949026, 'R@5': 0.015000000596046448, 'Hit@5': 0.015000000596046448, 'R@10': 0.02500000037252903, 'Hit@10': 0.02500000037252903}
Loading graphs from: /content/BornToOverfit/data_baseline/data/validation_graphs.pkl
Loaded 1000 graphs
Epoch 3/5 - loss=0.0001 - val={'MRR': 0.0120980991050601, 'R@1': 0.0020000000949949026, 'Hit@1'

In [12]:
!python data_baseline/retrieval_answer.py

Device: cuda
Loading model from /content/BornToOverfit/data_baseline/data/model_checkpoint.pt
Train set size: 31008
Loading graphs from: /content/BornToOverfit/data_baseline/data/test_graphs.pkl
Loaded 1000 graphs
Test set size: 1000
Encoded 1000 test molecules

Test ID 0: Retrieved from train ID 9397
Description: The molecule is an amino cyclitol glycoside that is 2-deoxystreptamine in which the pro-R hydroxy group is substituted by a 6-amino-6-deoxy-alpha-D-gl...

Test ID 1: Retrieved from train ID 12395
Description: The molecule is an L-isoleucine derivative that is L-isoleucine bearing a (4S)-hydroxy substituent. It has a role as a plant metabolite. It is an amin...

Test ID 2: Retrieved from train ID 12395
Description: The molecule is an L-isoleucine derivative that is L-isoleucine bearing a (4S)-hydroxy substituent. It has a role as a plant metabolite. It is an amin...

Test ID 3: Retrieved from train ID 12395
Description: The molecule is an L-isoleucine derivative that is L-isol

## Save results in drive

In [13]:
import shutil
import os

src = "/content/BornToOverfit/data_baseline/data/test_retrieved_descriptions.csv"

dst_dir = "/content/drive/MyDrive/Kaggle_ALTEGRAD/data/results"
new_name = "baseline.csv"  # 👈 nouveau nom

dst = os.path.join(dst_dir, new_name)

os.makedirs(dst_dir, exist_ok=True)
shutil.copy(src, dst)


'/content/drive/MyDrive/Kaggle_ALTEGRAD/data/results/baseline.csv'

### checkpoints entrainement

In [24]:
!ls -lh /content/BornToOverfit/data_baseline/data/ | grep checkpoint


-rw-r--r-- 1 root root 586K Dec 25 16:19 model_checkpoint.pt


In [26]:
!find /content/BornToOverfit/ -maxdepth 4 -type f \( -name "*.pt" -o -name "*.pth" -o -name "*.ckpt" \) -print -exec ls -lh {} \;


/content/BornToOverfit/data_baseline/data/model_checkpoint.pt
-rw-r--r-- 1 root root 586K Dec 25 16:19 /content/BornToOverfit/data_baseline/data/model_checkpoint.pt


In [27]:
import torch
path = "/content/BornToOverfit/data_baseline/data/model_checkpoint.pt"
ckpt = torch.load(path, map_location="cpu")
print(type(ckpt))


<class 'collections.OrderedDict'>


In [34]:

!cp /content/BornToOverfit/data_baseline/data/model_checkpoint.pt /content/drive/MyDrive/Kaggle_ALTEGRAD/data/model/model_checkpoint.pt



## Validation set test score

In [1]:
from google.colab import drive
drive.mount('/content/drive')

import os, sys
BASE = "/content/BornToOverfit/data_baseline"
DATA = f"{BASE}/data"

%cd {BASE}
sys.path.append(BASE)

print("Files in data/:")
!ls -lh {DATA} | head


Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
/content/BornToOverfit/data_baseline
Files in data/:
total 461M
-rw-r--r-- 1 root root 586K Dec 25 16:19 model_checkpoint.pt
-rw------- 1 root root 5.8M Dec 25 16:17 test_graphs.pkl
-rw-r--r-- 1 root root 286K Dec 25 16:28 test_retrieved_descriptions.csv
-rw------- 1 root root 257M Dec 25 16:17 train_embeddings.csv
-rw------- 1 root root 183M Dec 25 16:17 train_graphs.pkl
-rw------- 1 root root 8.3M Dec 25 16:17 validation_embeddings.csv
-rw------- 1 root root 6.3M Dec 25 16:17 validation_graphs.pkl


In [2]:
!python -m pip -q install -U evaluate bert-score sacrebleu


In [3]:
import evaluate
print("evaluate ok:", evaluate.__version__)


evaluate ok: 0.4.6


In [4]:
!cp /content/drive/MyDrive/Kaggle_ALTEGRAD/data/model/model_checkpoint_baseline.pt {DATA}/model_checkpoint.pt
!ls -lh {DATA}/model_checkpoint.pt


-rw-r--r-- 1 root root 586K Dec 25 16:54 /content/BornToOverfit/data_baseline/data/model_checkpoint.pt


In [5]:
import pickle
import numpy as np
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader
import evaluate

from data_utils import load_id2emb, load_descriptions_from_graphs, PreprocessedGraphDataset, collate_fn
from train_gcn import MolGNN

TRAIN_GRAPHS = f"{DATA}/train_graphs.pkl"
VAL_GRAPHS   = f"{DATA}/validation_graphs.pkl"
TRAIN_EMB_CSV= f"{DATA}/train_embeddings.csv"
MODEL_PATH   = f"{DATA}/model_checkpoint.pt"

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
print("DEVICE:", DEVICE)

@torch.no_grad()
def predict_val_retrieval():
    # Train text embeddings (targets)
    train_emb = load_id2emb(TRAIN_EMB_CSV)
    train_ids = list(train_emb.keys())
    train_embs = torch.stack([train_emb[i] for i in train_ids]).to(DEVICE)
    train_embs = F.normalize(train_embs, dim=-1)

    # Train id -> description (to output)
    train_id2desc = load_descriptions_from_graphs(TRAIN_GRAPHS)

    # Load model
    emb_dim = train_embs.shape[1]
    model = MolGNN(out_dim=emb_dim).to(DEVICE)
    state = torch.load(MODEL_PATH, map_location=DEVICE)
    model.load_state_dict(state)
    model.eval()

    # Validation graphs loader (only graphs)
    val_ds = PreprocessedGraphDataset(VAL_GRAPHS)
    val_dl = DataLoader(val_ds, batch_size=64, shuffle=False, collate_fn=collate_fn)

    # References (id -> true description)
    val_graphs = pickle.load(open(VAL_GRAPHS, "rb"))
    val_ref = {g.id: g.description for g in val_graphs}

    preds, refs = [], []
    offset = 0
    for batch in val_dl:
        batch = batch.to(DEVICE)
        mol_emb = model(batch)  # normalized in MolGNN
        sims = mol_emb @ train_embs.t()
        best = sims.argmax(dim=-1).cpu().tolist()

        bsz = batch.num_graphs
        batch_ids = val_ds.ids[offset:offset+bsz]
        offset += bsz

        for i, vid in enumerate(batch_ids):
            tid = train_ids[best[i]]
            preds.append(train_id2desc[tid])
            refs.append(val_ref[vid])

    return preds, refs

def compute_metrics(preds, refs):
    bleu = evaluate.load("bleu").compute(
        predictions=preds,
        references=[[r] for r in refs],
        max_order=4
    )["bleu"]  # parfois 0..1, parfois 0..100 selon version

    bert = evaluate.load("bertscore").compute(
        predictions=preds,
        references=refs,
        model_type="roberta-base",
        lang="en"
    )
    bert_f1 = float(np.mean(bert["f1"]))

    bleu_norm = bleu/100.0 if bleu > 1.0 else bleu
    final_proxy = 0.5*bleu_norm + 0.5*bert_f1
    return bleu, bert_f1, final_proxy

preds, refs = predict_val_retrieval()
bleu4, bert_f1, final_proxy = compute_metrics(preds, refs)

print("BLEU-4:", bleu4)
print("BERTScore F1:", bert_f1)
print("Final proxy (avg):", final_proxy)

print("\nExample:")
print("PRED:", preds[0][:200])
print("REF :", refs[0][:200])


DEVICE: cuda
Loading graphs from: /content/BornToOverfit/data_baseline/data/validation_graphs.pkl
Loaded 1000 graphs


/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/481 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/899k [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/499M [00:00<?, ?B/s]

Some weights of RobertaModel were not initialized from the model checkpoint at roberta-base and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


BLEU-4: 0.1635925936906004
BERTScore F1: 0.8695655007362366
Final proxy (avg): 0.5165790472134185

Example:
PRED: The molecule is an amino cyclitol glycoside that is 2-deoxystreptamine in which the pro-R hydroxy group is substituted by a 6-amino-6-deoxy-alpha-D-glucosyl residue. It has a role as an antimicrobial 
REF : The molecule is an amino tetrasaccharide comprised of an L-iduronic acid residue, sulfated on O-2, a glucuronic acid residue, and two N-acetylated galactosamine residues, one of which is at the reduci
