# **Running the KNN approach with the GPS graph encoder + GRALE**
<a target="_blank" href="https://colab.research.google.com/github/raphaelrubrice/BornToOverfit/blob/raph/GRALE_generate.ipynb"> <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/> </a>  

## **Colab setup**

In [1]:
from google.colab import drive
drive.mount('/content/drive')
# to avoid having the data on your drive
%cd /content

Mounted at /content/drive
/content


In [2]:
!git clone https://github.com/raphaelrubrice/BornToOverfit.git
%cd BornToOverfit
!git checkout raph

Cloning into 'BornToOverfit'...
remote: Enumerating objects: 256, done.
remote: Counting objects: 100% (58/58), done.
remote: Compressing objects: 100% (30/30), done.
remote: Total 256 (delta 36), reused 41 (delta 28), pack-reused 198 (from 1)
Receiving objects: 100% (256/256), 192.47 KiB | 1.53 MiB/s, done.
Resolving deltas: 100% (156/156), done.
/content/BornToOverfit
Branch 'raph' set up to track remote branch 'raph' from 'origin'.
Switched to a new branch 'raph'


Installing requirements

In [3]:
!pip install -r data_baseline/requirements.txt

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.7/63.7 kB 3.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 51.8/51.8 kB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 35.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.4/36.4 MB 77.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.1/59.1 MB 46.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 104.1/104.1 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.1/61.1 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.1/84.1 kB 9.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 518.9/518.9 kB 46.0 MB/s eta 0:00:00


Downloading the data

In [17]:
!cp -r /content/drive/MyDrive/MVA/ALTEGRAD/challenge_data/data /content/BornToOverfit/data_baseline/.

## **Scripts**

In [18]:
!python data_baseline/inspect_graph_data.py

INSPECTING GRAPH DATA FILES

Loading: /content/BornToOverfit/data_baseline/data/train_graphs.pkl
Total graphs: 31008

Graph type: Data

All graph attributes:
  ['description', 'x', 'edge_attr', 'id', 'edge_index']
Node features: torch.Size([40, 9])
Edge indices: torch.Size([2, 86])
Edge features: torch.Size([86, 3])

Sample graph:
  Graph 1:
    ID: 0
    Nodes: 40
    Edges: 86
    Node features (first 3 nodes):
tensor([[6, 0, 3, 5, 1, 0, 3, 1, 1],
        [7, 0, 2, 5, 0, 0, 3, 1, 1],
        [6, 0, 3, 5, 0, 0, 3, 1, 1]])
    Edge indices (first 5 edges):
tensor([[0, 0, 1, 1, 2],
        [1, 5, 0, 2, 1]])
    Edge attributes (first 5 edges):
tensor([[12,  0,  1],
        [12,  0,  1],
        [12,  0,  1],
        [12,  0,  1],
        [12,  0,  1]])
    Description: The molecule is tetraanion of ADP-D-ribose 2'-phosphate. It has a role as a human metabolite. It is a conjugate base of an ADP-D-ribose 2'-phosphate....

Nodes: min=1, max=574, avg=32.1
Edges: min=0, max=1284, avg=66.7
Gr

Add Molecule Cards

In [19]:
!python data_baseline/data_utils.py

BUILD + SAVE: mol_card for all graphs

[1/3] Loading: /content/BornToOverfit/data_baseline/data/train_graphs.pkl
Loaded graphs: 31008
Added/updated mol_card for: 31008
[2/3] Saving back to same location: /content/BornToOverfit/data_baseline/data/train_graphs.pkl
[3/3] Reloading to verify mol_card persisted: /content/BornToOverfit/data_baseline/data/train_graphs.pkl

--- Sample mol_card (first graph) ---
[MOL_FEATURES]
atoms_total: 40
elements: C=15 N=5 O=17 P=3
halogens_total: 0
metals_or_other_total: 0
formal_charge_net: -4
aromatic_atoms: 9
ring_atoms: 19
undirected_bonds: 43
bond_types: SINGLE=30 DOUBLE=3 AROMATIC=10
conjugated_bonds: 11
hybridization: SP2=13 SP3=27
degree_hist: 1=7 2=13 3=7 4=13
num_hs_hist: 0=23 1=14 2=3
chirality_centers: 7
radical_atoms: 0
tags: net_negative_charge(-4); contains_P_and_O; aromatic_character; ring_system; heteroatom_rich
[/MOL_FEATURES]

--- Ground-truth description (truncated) ---
The molecule is tetraanion of ADP-D-ribose 2'-phosphate. It has a 

Traing custom GrALE-like model and the Graph -> LLM projector

In [ ]:
!python prototype/graph_llm_aligned.py -f prototype/grale_knn/ -base_llm deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B

Obtain embeddings

In [31]:
!python data_baseline/generate_description_embeddings.py -f prototype/grale_knn/ --base_model QizhiPei/biot5-plus-base

2025-12-28 19:47:42.621580: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-28 19:47:42.639784: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1766951262.661489   30739 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1766951262.668089   30739 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1766951262.684923   30739 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

Traing the Graph encoder

In [32]:
!python data_baseline/train_gcn_v3_gps.py -f prototype/grale_knn/ -loss infonce

TRAINING MolGNN v3 - GPS Transformer
Data: /content/BornToOverfit/data_baseline/data
Output: /content/BornToOverfit/prototype/gps_knn
Device: cuda, Hidden: 256, Heads: 4, Layers: 4
TRAIN EMB /content/BornToOverfit/prototype/gps_knn/train_embeddings.csv
VAL EMB /content/BornToOverfit/prototype/gps_knn/validation_embeddings.csv
Loading graphs from: /content/BornToOverfit/data_baseline/data/train_graphs.pkl
Loaded 31008 graphs
Loading graphs from: /content/BornToOverfit/data_baseline/data/validation_graphs.pkl
Loaded 1000 graphs
Parameters: 3,745,540
Epoch 1/50 | loss=0.0003 | MRR: 0.0134 | R@1: 0.0010 | Hit@1: 0.0010 | R@5: 0.0120 | Hit@5: 0.0120 | R@10: 0.0290 | Hit@10: 0.0290
  → New best MRR: 0.0134
Epoch 2/50 | loss=0.0002 | MRR: 0.0180 | R@1: 0.0040 | Hit@1: 0.0040 | R@5: 0.0170 | Hit@5: 0.0170 | R@10: 0.0340 | Hit@10: 0.0340
  → New best MRR: 0.0180
Epoch 3/50 | loss=0.0002 | MRR: 0.0256 | R@1: 0.0080 | Hit@1: 0.0080 | R@5: 0.0290 | Hit@5: 0.0290 | R@10: 0.0520 | Hit@10: 0.0520
  →

Fine-tune the LLM with SFT + PPO

In [22]:
!python prototype/knn_tanimoto_grale_generate.py -f_data data_baseline/data -f prototype/grale_knn/ \
  --do_finetune \
  --do_sft \
  --k 5 \
  --use_lora \
  --sft_steps 500 \
  --sft_lora 16 \
  --per_device_bs 1 \
  --grad_accum 8 \
  --base_llm grale \
  --out_llm_dir knn_llm \
  --max_prompt_length 2048

2025-12-28 18:35:01.816276: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-28 18:35:01.834683: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1766946901.856511   12362 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1766946901.863129   12362 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1766946901.879848   12362 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

Generate on validation with the fine-tuned model + evaluation metrics

In [23]:
!python prototype/knn_generate.py -f_data data_baseline/data -f prototype/grale_knn/ \
  --do_generate --split validation --k 5 \
  --gen_batch_size 8 \
  --out_llm_dir grale_knn_llm_sft \
  --max_prompt_length 2048

2025-12-28 18:35:42.317268: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-28 18:35:42.334239: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1766946942.355167   12572 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1766946942.361556   12572 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1766946942.377316   12572 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

Generate on test (no references; no evaluation)

In [24]:
!python prototype/knn_generate.py -f_data data_baseline/data -f prototype/grale_knn/ \
  --do_generate --split test --k 5 \
  --gen_batch_size 8 \
  --out_llm_dir grale_knn_llm_sft \
  --max_prompt_length 2048

2025-12-28 18:36:18.748409: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-12-28 18:36:18.766516: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
E0000 00:00:1766946978.787917   12794 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1766946978.794409   12794 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1766946978.810782   12794 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking 

See generated data on the test set

In [25]:
import pandas as pd
test = pd.read_csv("/content/BornToOverfit/prototype/grale_knn/test_knn_gen_k5.csv")
test

FileNotFoundError: [Errno 2] No such file or directory: '/content/BornToOverfit/prototype/gps_knn/test_knn_gen_k5.csv'

In [ ]:
print(test.iloc[18]["Prompt"])
print(test.iloc[18]["generated_description"])

Saving to Drive

In [ ]:
!cp -r /content/BornToOverfit/prototype/grale_knn /content/drive/MyDrive/MVA/ALTEGRAD/challenge_data/.